llanguage: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t yds5539/node-test ./back-end

script:
  - docker run -e CI=true yds5539/node-test npm run test

after_success:
  - docker build -t yds5539/node-health ./back-end

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push yds5539/node-health
  
# deploy:
#   provider: elasticbeanstalk
#   region: "ap-northeast-2"
#   app: "docker-fullstack-app"
#   env: "DockerFullstackApp-env"
#   bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
#   bucket_path: "docker-fullstack-app"
#   on:
#     branch: master
  
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_ACCESS_KEY