version: '2'

services:
  node_health:
    image: health-image
    environment:
      - COOKIE_SECRET=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_NAME=
      - DB_HOST=
      - JWT_SECRET=
      - ACCESSTOKEN_EXPIRE=
      - REFRESHTOKEN_EXPIRE=
    container_name: blue
    volumes:
      - /home/ubuntu/deploy/node_health:/deploy/node_health
    ports:
      - "8001:8005"    
